import { PostData, CommentData, RedditUser } from '@/api/reddit';

export const mockUser: RedditUser = {
  id: 'mock_user_1',
  name: '4rCH133',
  icon_img: '',
  total_karma: 48291,
  link_karma: 32100,
  comment_karma: 16191,
  created_utc: 1513728000,
  is_gold: false,
  verified: true,
};

export const mockPosts: PostData[] = [
  {
    id: 'mock1',
    name: 't3_mock1',
    title: 'The James Webb Space Telescope just captured the deepest infrared image of the universe ever taken',
    author: 'space_nerd_42',
    subreddit: 'space',
    subreddit_name_prefixed: 'r/space',
    selftext: '',
    url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/James_Webb_Space_Telescope_and_Newton%27s_prism.jpg/800px-James_Webb_Space_Telescope_and_Newton%27s_prism.jpg',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/James_Webb_Space_Telescope_and_Newton%27s_prism.jpg/800px-James_Webb_Space_Telescope_and_Newton%27s_prism.jpg',
    preview: {
      images: [{
        source: {
          url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/James_Webb_Space_Telescope_and_Newton%27s_prism.jpg/800px-James_Webb_Space_Telescope_and_Newton%27s_prism.jpg',
          width: 800,
          height: 500,
        }
      }]
    },
    score: 142800,
    upvote_ratio: 0.97,
    num_comments: 3241,
    created_utc: Date.now() / 1000 - 3600 * 4,
    permalink: '/r/space/comments/mock1',
    is_self: false,
    likes: null,
    saved: false,
    over_18: false,
    stickied: false,
    is_video: false,
    post_hint: 'image',
    link_flair_text: 'Image',
  },
  {
    id: 'mock2',
    name: 't3_mock2',
    title: 'I built a React Native Reddit client from scratch — here\'s what I learned about performance optimization',
    author: '4rCH133',
    subreddit: 'reactnative',
    subreddit_name_prefixed: 'r/reactnative',
    selftext: 'After months of development, I want to share the key lessons learned building a high-performance Reddit client with FlashList, TanStack Query, and SQLite FTS5 for offline search.\n\nThe biggest win was switching from FlatList to FlashList — immediately got 60fps scrolling on both platforms.',
    url: 'https://reddit.com/r/reactnative/comments/mock2',
    thumbnail: 'self',
    score: 8420,
    upvote_ratio: 0.94,
    num_comments: 312,
    created_utc: Date.now() / 1000 - 3600 * 9,
    permalink: '/r/reactnative/comments/mock2',
    is_self: true,
    likes: true,
    saved: true,
    over_18: false,
    stickied: false,
    is_video: false,
    link_flair_text: 'Project',
  },
  {
    id: 'mock3',
    name: 't3_mock3',
    title: 'Apple reportedly planning thinnest iPhone ever for 2025 — codenamed "iPhone Air"',
    author: 'tech_leaker99',
    subreddit: 'apple',
    subreddit_name_prefixed: 'r/apple',
    selftext: '',
    url: 'https://9to5mac.com',
    thumbnail: 'default',
    score: 34100,
    upvote_ratio: 0.89,
    num_comments: 1872,
    created_utc: Date.now() / 1000 - 3600 * 2,
    permalink: '/r/apple/comments/mock3',
    is_self: false,
    likes: null,
    saved: false,
    over_18: false,
    stickied: false,
    is_video: false,
    link_flair_text: 'Rumor',
  },
  {
    id: 'mock4',
    name: 't3_mock4',
    title: 'My dog learned to open the fridge. I have made a terrible mistake.',
    author: 'dogdad_forever',
    subreddit: 'dogs',
    subreddit_name_prefixed: 'r/dogs',
    selftext: '',
    url: 'https://i.imgur.com/example.jpg',
    thumbnail: 'https://placedog.net/500/300',
    preview: {
      images: [{
        source: {
          url: 'https://placedog.net/500/300',
          width: 500,
          height: 300,
        }
      }]
    },
    score: 91200,
    upvote_ratio: 0.99,
    num_comments: 742,
    created_utc: Date.now() / 1000 - 3600 * 1,
    permalink: '/r/dogs/comments/mock4',
    is_self: false,
    likes: true,
    saved: false,
    over_18: false,
    stickied: false,
    is_video: false,
    link_flair_text: null,
  },
  {
    id: 'mock5',
    name: 't3_mock5',
    title: 'PSA: You can search your entire upvote history instantly with Orca — no API calls needed',
    author: 'orca_beta_user',
    subreddit: 'redditmobile',
    subreddit_name_prefixed: 'r/redditmobile',
    selftext: 'Just discovered that Orca indexes all your upvoted posts locally using SQLite FTS5. Searched through 3 years of upvotes in under 100ms. This is the feature I\'ve always wanted.',
    url: 'https://reddit.com/r/redditmobile/comments/mock5',
    thumbnail: 'self',
    score: 2841,
    upvote_ratio: 0.97,
    num_comments: 89,
    created_utc: Date.now() / 1000 - 3600 * 6,
    permalink: '/r/redditmobile/comments/mock5',
    is_self: true,
    likes: null,
    saved: false,
    over_18: false,
    stickied: false,
    is_video: false,
    link_flair_text: 'App',
  },
];

export const mockComments: CommentData[] = [
  {
    id: 'mc1',
    body: 'This is absolutely incredible. The level of detail is mind-blowing — you can see individual galaxies that are billions of light years away.',
    author: 'astronomy_lover',
    score: 12400,
    created_utc: Date.now() / 1000 - 3600 * 3,
    depth: 0,
    likes: null,
    is_submitter: false,
    replies: {
      data: {
        after: null,
        before: null,
        children: [
          {
            kind: 't1',
            data: {
              id: 'mc1a',
              body: 'And to think each of those tiny dots of light is an entire galaxy containing hundreds of billions of stars. Reality is surreal.',
              author: 'cosmos_watcher',
              score: 4200,
              created_utc: Date.now() / 1000 - 3600 * 2,
              depth: 1,
              likes: true,
              is_submitter: false,
              replies: '',
            } as CommentData,
          },
          {
            kind: 't1',
            data: {
              id: 'mc1b',
              body: 'The Hubble Deep Field image was already mind-blowing. This makes that look like a rough draft.',
              author: 'deep_field_fan',
              score: 2810,
              created_utc: Date.now() / 1000 - 3600 * 2.5,
              depth: 1,
              likes: null,
              is_submitter: false,
              replies: '',
            } as CommentData,
          },
        ],
      },
    },
  },
  {
    id: 'mc2',
    body: 'As someone who works in astrophysics, seeing public excitement about JWST never gets old. The science coming out of this telescope is going to redefine our understanding of the early universe.',
    author: 'dr_stargazer',
    score: 8901,
    created_utc: Date.now() / 1000 - 3600 * 3.5,
    depth: 0,
    likes: null,
    is_submitter: false,
    replies: {
      data: {
        after: null,
        before: null,
        children: [
          {
            kind: 't1',
            data: {
              id: 'mc2a',
              body: 'What\'s the most surprising finding so far from your perspective?',
              author: 'curious_mind_99',
              score: 1200,
              created_utc: Date.now() / 1000 - 3600 * 2,
              depth: 1,
              likes: null,
              is_submitter: false,
              replies: '',
            } as CommentData,
          },
        ],
      },
    },
  },
  {
    id: 'mc3',
    body: 'I showed this to my 6-year-old and she asked "are we in one of those?" I had to sit down for a minute.',
    author: 'parent_of_wonder',
    score: 31200,
    created_utc: Date.now() / 1000 - 3600 * 1,
    depth: 0,
    likes: true,
    is_submitter: false,
    replies: '',
  },
];
